// Governing: ADR-0014, SPEC-0010 REQ "Record Content Pipeline"
// Governing: ADR-0014, SPEC-0010 REQ "Derived Data Module"
//
// Writing the staged tree and the derived data module.
//
// Two rules shape this file.
//
// The record body is copied byte-for-byte. Only front-matter is replaced, and
// the replacement carries nothing but what the *renderer* needs. The record's
// own front-matter — `decision-makers`, the authoring comments — is not
// republished, and the body is never rewritten, because "record source files
// remain plain CommonMark" is only true if nothing edits them on the way out.
//
// Nothing is written that has not changed. The staged tree lives inside the
// documentation content root, which the docs plugin watches, so a rewrite with
// identical bytes would still bounce the dev server. Stale files left over from
// a previous run are removed instead of the tree being wiped, for the same
// reason.

import fs from 'node:fs/promises';
import path from 'node:path';

import {
  DECISIONS_SEGMENT,
  SPECS_SEGMENT,
  type RecordPaths,
} from './paths.ts';
import type {RecordData} from './types.ts';

const GENERATED_NOTICE = (sourcePath: string): string[] => [
  `# GENERATED by website/plugins/record — do not edit, and do not commit.`,
  `# Source of truth: ${sourcePath}`,
];

/** Positions that keep the two generated groups after the narrative pages. */
export const DECISIONS_SIDEBAR_POSITION = 100;
export const SPECS_SIDEBAR_POSITION = 110;

interface StagedFile {
  absPath: string;
  contents: string;
}

/**
 * Serialise a front-matter value. Deliberately minimal rather than pulling in a
 * YAML emitter: every value the pipeline writes is a string or a number, and a
 * single-quoted scalar with doubled quotes is valid YAML for any of them.
 */
function yamlScalar(value: string | number): string {
  if (typeof value === 'number') {
    return String(value);
  }
  return `'${value.replace(/'/g, "''")}'`;
}

function frontMatter(
  notice: string[],
  fields: Record<string, string | number | undefined>,
): string {
  const lines = ['---', ...notice];
  for (const [key, value] of Object.entries(fields)) {
    if (value !== undefined) {
      lines.push(`${key}: ${yamlScalar(value)}`);
    }
  }
  lines.push('---', '', '');
  return lines.join('\n');
}

/**
 * A staged record page: replacement front-matter, then the record body exactly
 * as authored.
 */
function recordPage(
  sourcePath: string,
  fields: Record<string, string | number | undefined>,
  body: string,
): string {
  return `${frontMatter(GENERATED_NOTICE(sourcePath), fields)}${body.replace(/^\n+/, '')}`;
}

export interface StageInput {
  paths: RecordPaths;
  data: RecordData;
  /** Record bodies, keyed by record id, plus the paired design bodies. */
  bodies: Map<string, {sourcePath: string; body: string}>;
  designBodies: Map<string, {sourcePath: string; body: string; title: string}>;
}

/**
 * Stage the whole record and write the derived data module.
 *
 * @returns the absolute paths written, for the caller to log or assert on.
 */
export async function stageRecord({
  paths,
  data,
  bodies,
  designBodies,
}: StageInput): Promise<string[]> {
  const files: StagedFile[] = [];

  files.push({
    absPath: path.join(paths.stagedDecisionsDir, '_category_.json'),
    contents: `${JSON.stringify(
      {
        label: `Decisions · ${data.counts.decisions}`,
        position: DECISIONS_SIDEBAR_POSITION,
        collapsed: true,
      },
      null,
      2,
    )}\n`,
  });

  files.push({
    absPath: path.join(paths.stagedDecisionsDir, 'index.mdx'),
    contents: decisionsIndexPage(),
  });

  for (const decision of data.decisions) {
    const source = bodies.get(decision.id);
    if (!source) {
      throw new Error(`No body staged for ${decision.id}`);
    }
    files.push({
      absPath: path.join(paths.stagedDecisionsDir, `${decision.id}.md`),
      contents: recordPage(
        source.sourcePath,
        {
          title: `${decision.id}: ${decision.title}`,
          sidebar_label: decision.id,
          sidebar_position: decision.number,
          description: decision.summary || undefined,
        },
        source.body,
      ),
    });
  }

  files.push({
    absPath: path.join(paths.stagedSpecsDir, '_category_.json'),
    contents: `${JSON.stringify(
      {
        label: `Specifications · ${data.counts.specifications}`,
        position: SPECS_SIDEBAR_POSITION,
        collapsed: true,
      },
      null,
      2,
    )}\n`,
  });

  files.push({
    absPath: path.join(paths.stagedSpecsDir, 'index.mdx'),
    contents: specsIndexPage(),
  });

  for (const spec of data.specs) {
    const dir = path.join(paths.stagedSpecsDir, spec.capability);
    files.push({
      absPath: path.join(dir, '_category_.json'),
      contents: `${JSON.stringify(
        {
          label: `${spec.id} · ${spec.title}`,
          position: spec.number,
          collapsed: true,
        },
        null,
        2,
      )}\n`,
    });

    const source = bodies.get(spec.id);
    if (!source) {
      throw new Error(`No body staged for ${spec.id}`);
    }
    files.push({
      absPath: path.join(dir, 'index.md'),
      contents: recordPage(
        source.sourcePath,
        {
          title: `${spec.id}: ${spec.title}`,
          sidebar_label: spec.id,
          sidebar_position: 1,
          description: spec.summary || undefined,
        },
        source.body,
      ),
    });

    const design = designBodies.get(spec.id);
    if (design) {
      files.push({
        absPath: path.join(dir, 'design.md'),
        contents: recordPage(
          design.sourcePath,
          {
            title: design.title,
            sidebar_label: 'Design',
            sidebar_position: 2,
            description: `Design document for ${spec.id}: ${spec.title}.`,
          },
          design.body,
        ),
      });
    }
  }

  files.push({
    absPath: paths.recordJson,
    contents: `${JSON.stringify(data, null, 2)}\n`,
  });

  await writeStaged(paths, files);
  return files.map((file) => file.absPath);
}

/**
 * The decisions index. Staged as `.mdx` on purpose: it holds no record prose, so
 * it is safe to write component markup into it, and it therefore needs none of
 * the AST machinery the record pages do.
 */
function decisionsIndexPage(): string {
  return `${frontMatter(
    [`# GENERATED by website/plugins/record — do not edit, and do not commit.`],
    {
      title: 'Decisions',
      sidebar_label: 'All decisions',
      sidebar_position: 0,
      description: `Every architecture decision record Cairn has accepted, published in full from the repository's own record.`,
    },
  )}import {DecisionIndex} from '@site/src/components/record/indexes';

# Decisions

<DecisionIndex />
`;
}

function specsIndexPage(): string {
  return `${frontMatter(
    [`# GENERATED by website/plugins/record — do not edit, and do not commit.`],
    {
      title: 'Specifications',
      sidebar_label: 'All specifications',
      sidebar_position: 0,
      description: `Every Cairn capability specification, with its requirement count derived from the specification itself.`,
    },
  )}import {SpecIndex} from '@site/src/components/record/indexes';

# Specifications

<SpecIndex />
`;
}

/**
 * Write the staged files, skipping any whose bytes are unchanged, then delete
 * anything left in the staged trees that this run did not write.
 */
async function writeStaged(
  paths: RecordPaths,
  files: StagedFile[],
): Promise<void> {
  const written = new Set(files.map((file) => path.resolve(file.absPath)));

  for (const file of files) {
    await fs.mkdir(path.dirname(file.absPath), {recursive: true});
    let existing: string | null = null;
    try {
      existing = await fs.readFile(file.absPath, 'utf8');
    } catch {
      existing = null;
    }
    if (existing !== file.contents) {
      await fs.writeFile(file.absPath, file.contents, 'utf8');
    }
  }

  for (const root of [paths.stagedDecisionsDir, paths.stagedSpecsDir]) {
    await pruneStale(root, written);
  }
}

async function pruneStale(root: string, keep: Set<string>): Promise<void> {
  let entries;
  try {
    entries = await fs.readdir(root, {withFileTypes: true});
  } catch {
    return;
  }
  for (const entry of entries) {
    const abs = path.join(root, entry.name);
    if (entry.isDirectory()) {
      await pruneStale(abs, keep);
      const remaining = await fs.readdir(abs);
      if (remaining.length === 0) {
        await fs.rmdir(abs);
      }
      continue;
    }
    if (!keep.has(path.resolve(abs))) {
      await fs.rm(abs);
    }
  }
}

/** Route of a staged decision page. */
export function decisionHref(routeBase: string, id: string): string {
  return `${routeBase}/${DECISIONS_SEGMENT}/${id}`;
}

/** Route of a staged specification page. */
export function specHref(routeBase: string, capability: string): string {
  return `${routeBase}/${SPECS_SEGMENT}/${capability}`;
}

export function decisionDocId(id: string): string {
  return `${DECISIONS_SEGMENT}/${id}`;
}

export function specDocId(capability: string): string {
  return `${SPECS_SEGMENT}/${capability}/index`;
}

export function designDocId(capability: string): string {
  return `${SPECS_SEGMENT}/${capability}/design`;
}
