import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Governing: ADR-0014, SPEC-0010 REQ "Derived Data Module"
//
// One autogenerated sidebar over the whole documentation content root, spanning
// the tracked narrative pages and the git-ignored staged record alike. No record
// document is enumerated here, and none may be: adding a decision must publish
// it with zero edits under `website/`.
//
// This file cannot read the derived data module, and no amount of cleverness
// changes that. `sidebars.ts` is loaded Node-side from inside the docs plugin's
// own content-loading path (`plugin-content-docs/lib/sidebars/index.js`:
// `loadSidebarsFileUnsafe` → `loadFreshModule`) and is consumed as a *value*,
// never invoked, so an exported function is not a way in either. That load runs
// concurrently with the record plugin's `loadContent()` and strictly before any
// `contentLoaded()`, so there is no ordering in which an import of the data
// module would be current.
//
// The group labels and their counts therefore come from `_category_.json` files
// that the pipeline writes into the staged directories, which are on disk before
// the docs plugin reads them because generation happens at config-load time.
// `dirName: '.'` rather than one autogenerated item per staged tree: an
// autogenerated item rooted *at* a directory splices that directory's contents in
// flat and never consults its `_category_.json`, which would throw the derived
// labels away.
//
// Narrative page ordering comes from the `sidebar_position` front-matter those
// pages already carry.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
