import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Governing: ADR-0014, SPEC-0010 REQ "Derived Data Module"
// Governing: ADR-0014, SPEC-0010 REQ "Record Navigation"
//
// One autogenerated sidebar over the whole documentation content root, spanning
// the tracked narrative pages and the git-ignored staged record alike. No record
// document is enumerated here, and none may be: adding a decision must publish
// it with zero edits under `website/`.
//
// This file cannot read the derived data module, and no amount of cleverness
// changes that. `sidebars.ts` is loaded Node-side from inside the docs plugin's
// own content-loading path (`plugin-content-docs/lib/sidebars/index.js`:
// `loadSidebarsFileUnsafe` → `loadFreshModule`) and is consumed as a *value*,
// never invoked, so an exported function is not a way in either. That load runs
// concurrently with the record plugin's `loadContent()` and strictly before any
// `contentLoaded()`, so there is no ordering in which an import of the data
// module would be current.
//
// The group labels and their counts therefore come from `_category_.json` files
// that the pipeline writes into the staged directories, which are on disk before
// the docs plugin reads them because generation happens at config-load time.
// `dirName: '.'` rather than one autogenerated item per staged tree: an
// autogenerated item rooted *at* a directory splices that directory's contents in
// flat and never consults its `_category_.json`, which would throw the derived
// labels away.
//
// INFORMATION ARCHITECTURE. `dirName: '.'` is what makes the record self-
// publishing, but taken alone it also flattened the narrative pages into a row
// of four unrelated top-level entries, losing the Product grouping the site had
// before the pipeline landed. The fix is a directory rather than a hand-written
// item list, because a hand-written list is a second place a page has to be
// registered — the exact failure ADR-0014 exists to abolish, one layer up from
// the index tables. `website/docs/product/` therefore carries the three product
// pages and a tracked `_category_.json` that names the group, and the sidebar
// reads:
//
//     Overview                       docs/intro.md
//     Product                        docs/product/_category_.json  (tracked)
//       Share types · Surfaces · Annotations · Tags & handoffs · Errors
//     Decisions · 14                 staged _category_.json        (derived)
//       ADR-0001 … ADR-0014
//     Specifications · 10            staged _category_.json        (derived)
//       SPEC-0001 … SPEC-0010, each with its Design document
//
// Those three pages keep their original routes — `/docs/share-types`, not
// `/docs/product/share-types` — through a `slug:` in their front-matter. The
// sidebar grouping is an authoring concern and has no business rewriting a URL
// that is already published and already linked from the homepage and the footer.
//
// A future reference tree needs no edit here either: stage it as a directory
// under `website/docs/` with a `_category_.json` and it appears.
//
// Narrative page ordering comes from the `sidebar_position` front-matter those
// pages already carry; group ordering from `position` in each `_category_.json`.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
